// Mapeo corregido y completo para geoData.ts
// Este mapeo incluye todos los países del GeoJSON con traducciones al español apropiadas

const updatedCountryNameMap = {
	// Países principales ya existentes
	Afghanistan: "Afganistán",
	Albania: "Albania",
	Algeria: "Argelia",
	Angola: "Angola",
	Antarctica: "Antártida",
	Argentina: "Argentina",
	Armenia: "Armenia",
	Australia: "Australia",
	Austria: "Austria",
	Azerbaijan: "Azerbaiyán",
	Bangladesh: "Bangladés",
	Belarus: "Bielorrusia",
	Belgium: "Bélgica",
	Belize: "Belice",
	Benin: "Benín",
	Bhutan: "Bután",
	Bolivia: "Bolivia",
	"Bosnia and Herzegovina": "Bosnia y Herzegovina",
	Botswana: "Botsuana",
	Brazil: "Brasil",
	Brunei: "Brunéi",
	Bulgaria: "Bulgaria",
	"Burkina Faso": "Burkina Faso",
	Burundi: "Burundi",
	Cambodia: "Camboya",
	Cameroon: "Camerún",
	Canada: "Canadá",
	"Central African Republic": "República Centroafricana",
	Chad: "Chad",
	Chile: "Chile",
	China: "China",
	Colombia: "Colombia",
	Comoros: "Comoras",
	"Democratic Republic of the Congo": "República Democrática del Congo",
	"Republic of the Congo": "República del Congo",
	"Costa Rica": "Costa Rica",
	Croatia: "Croacia",
	Cuba: "Cuba",
	Cyprus: "Chipre",
	Denmark: "Dinamarca",
	Djibouti: "Yibuti",
	Dominica: "Dominica",
	"Dominican Republic": "República Dominicana",
	"East Timor": "Timor Oriental",
	Ecuador: "Ecuador",
	Egypt: "Egipto",
	"El Salvador": "El Salvador",
	"Equatorial Guinea": "Guinea Ecuatorial",
	Eritrea: "Eritrea",
	Estonia: "Estonia",
	Ethiopia: "Etiopía",
	Fiji: "Fiyi",
	Finland: "Finlandia",
	France: "Francia",
	"French Southern and Antarctic Lands":
		"Tierras Australes y Antárticas Francesas",
	Gabon: "Gabón",
	Georgia: "Georgia",
	Germany: "Alemania",
	Ghana: "Ghana",
	Greece: "Grecia",
	Greenland: "Groenlandia",
	Grenada: "Granada",
	Guatemala: "Guatemala",
	Guinea: "Guinea",
	"Guinea-Bissau": "Guinea-Bisáu",
	Guyana: "Guyana",
	Haiti: "Haití",
	Honduras: "Honduras",
	Hungary: "Hungría",
	Iceland: "Islandia",
	India: "India",
	Indonesia: "Indonesia",
	Iran: "Irán",
	Iraq: "Irak",
	Ireland: "Irlanda",
	Israel: "Israel",
	Italy: "Italia",
	Jamaica: "Jamaica",
	Japan: "Japón",
	Jordan: "Jordania",
	Kazakhstan: "Kazajistán",
	Kenya: "Kenia",
	Kiribati: "Kiribati",
	Kuwait: "Kuwait",
	Kyrgyzstan: "Kirguistán",
	Laos: "Laos",
	Latvia: "Letonia",
	Lebanon: "Líbano",
	Lesotho: "Lesoto",
	Liberia: "Liberia",
	Libya: "Libia",
	Liechtenstein: "Liechtenstein",
	Lithuania: "Lituania",
	Luxembourg: "Luxemburgo",
	Madagascar: "Madagascar",
	Malawi: "Malaui",
	Malaysia: "Malasia",
	Maldives: "Maldivas",
	Mali: "Malí",
	Malta: "Malta",
	"Marshall Islands": "Islas Marshall",
	Mauritania: "Mauritania",
	Mauritius: "Mauricio",
	Mexico: "México",
	Moldova: "Moldavia",
	Monaco: "Mónaco",
	Mongolia: "Mongolia",
	Montenegro: "Montenegro",
	Morocco: "Marruecos",
	Mozambique: "Mozambique",
	Myanmar: "Birmania",
	Namibia: "Namibia",
	Nauru: "Nauru",
	Nepal: "Nepal",
	Netherlands: "Países Bajos",
	"New Zealand": "Nueva Zelanda",
	Nicaragua: "Nicaragua",
	Niger: "Níger",
	Nigeria: "Nigeria",
	"North Korea": "Corea del Norte",
	Norway: "Noruega",
	Oman: "Omán",
	Pakistan: "Pakistán",
	Palau: "Palaos",
	Palestine: "Palestina",
	Panama: "Panamá",
	"Papua New Guinea": "Papúa Nueva Guinea",
	Paraguay: "Paraguay",
	Peru: "Perú",
	Philippines: "Filipinas",
	Poland: "Polonia",
	Portugal: "Portugal",
	Qatar: "Catar",
	Romania: "Rumania",
	Russia: "Rusia",
	Rwanda: "Ruanda",
	"Saint Kitts and Nevis": "San Cristóbal y Nieves",
	"Saint Lucia": "Santa Lucía",
	"Saint Vincent and the Grenadines": "San Vicente y las Granadinas",
	Samoa: "Samoa",
	"San Marino": "San Marino",
	"Saudi Arabia": "Arabia Saudí",
	Senegal: "Senegal",
	Seychelles: "Seychelles",
	"Sierra Leone": "Sierra Leona",
	Singapore: "Singapur",
	Slovakia: "Eslovaquia",
	Slovenia: "Eslovenia",
	"Solomon Islands": "Islas Salomón",
	Somalia: "Somalia",
	"South Africa": "Sudáfrica",
	"South Korea": "Corea del Sur",
	"South Sudan": "Sudán del Sur",
	Spain: "España",
	"Sri Lanka": "Sri Lanka",
	Sudan: "Sudán",
	Suriname: "Surinam",
	Sweden: "Suecia",
	Switzerland: "Suiza",
	Syria: "Siria",
	Taiwan: "Taiwán",
	Tajikistan: "Tayikistán",
	Thailand: "Tailandia",
	Togo: "Togo",
	Tonga: "Tonga",
	"Trinidad and Tobago": "Trinidad y Tobago",
	Tunisia: "Túnez",
	Turkey: "Turquía",
	Turkmenistan: "Turkmenistán",
	Tuvalu: "Tuvalu",
	Uganda: "Uganda",
	Ukraine: "Ucrania",
	"United Arab Emirates": "Emiratos Árabes Unidos",
	"United Kingdom": "Reino Unido",
	"United States of America": "Estados Unidos",
	Uruguay: "Uruguay",
	Uzbekistan: "Uzbekistán",
	Vanuatu: "Vanuatu",
	Venezuela: "Venezuela",
	Vietnam: "Vietnam",
	Yemen: "Yemen",
	Zambia: "Zambia",
	Zimbabwe: "Zimbabue",

	// CORRECCIONES para países que aparecen diferente en GeoJSON
	eSwatini: "Esuatini", // En lugar de "Swaziland"
	"Ivory Coast": "Costa de Marfil", // En lugar de "Côte d'Ivoire"
	Czechia: "República Checa", // En lugar de "Czech Republic"
	Gambia: "Gambia", // En lugar de "The Gambia"
	"North Macedonia": "Macedonia del Norte", // En lugar de "Macedonia"
	"Federated States of Micronesia": "Micronesia", // En lugar de "Micronesia"
	"São Tomé and Principe": "Santo Tomé y Príncipe", // En lugar de "São Tomé and Príncipe"
	"Republic of Serbia": "Serbia", // En lugar de "Serbia"
	"United Republic of Tanzania": "Tanzania", // En lugar de "Tanzania"
	Vatican: "Ciudad del Vaticano", // En lugar de "Vatican City"

	// TERRITORIOS Y DEPENDENCIAS (traducciones apropiadas)
	Aland: "Islas Åland",
	"American Samoa": "Samoa Americana",
	Andorra: "Andorra",
	Anguilla: "Anguila",
	"Antigua and Barbuda": "Antigua y Barbuda",
	Aruba: "Aruba",
	Bahrain: "Baréin",
	Barbados: "Barbados",
	Bermuda: "Bermudas",
	"British Virgin Islands": "Islas Vírgenes Británicas",
	"Cabo Verde": "Cabo Verde",
	"Cayman Islands": "Islas Caimán",
	"Cook Islands": "Islas Cook",
	Curaçao: "Curazao",
	"Falkland Islands": "Islas Malvinas",
	"Faroe Islands": "Islas Feroe",
	"French Polynesia": "Polinesia Francesa",
	Gibraltar: "Gibraltar",
	Guam: "Guam",
	Guernsey: "Guernsey",
	"Hong Kong S.A.R.": "Hong Kong",
	"Isle of Man": "Isla de Man",
	Jersey: "Jersey",
	Kosovo: "Kosovo",
	"Macao S.A.R": "Macao",
	Montserrat: "Montserrat",
	"New Caledonia": "Nueva Caledonia",
	Niue: "Niue",
	"Norfolk Island": "Isla Norfolk",
	"Northern Cyprus": "Chipre del Norte",
	"Northern Mariana Islands": "Islas Marianas del Norte",
	"Pitcairn Islands": "Islas Pitcairn",
	"Puerto Rico": "Puerto Rico",
	"Saint Barthelemy": "San Bartolomé",
	"Saint Helena": "Santa Elena",
	"Saint Martin": "San Martín",
	"Saint Pierre and Miquelon": "San Pedro y Miquelón",
	"Sint Maarten": "Sint Maarten",
	Somaliland: "Somalilandia",
	"South Georgia and the Islands": "Georgia del Sur e Islas Sandwich del Sur",
	"Turks and Caicos Islands": "Islas Turcas y Caicos",
	"United States Virgin Islands": "Islas Vírgenes de los Estados Unidos",
	"Wallis and Futuna": "Wallis y Futuna",
	"Western Sahara": "Sáhara Occidental",

	// TERRITORIOS ESPECIALES Y BASES (mantener en inglés o traducir mínimamente)
	"Akrotiri Sovereign Base Area": "Base Soberana de Akrotiri",
	"Ashmore and Cartier Islands": "Islas Ashmore y Cartier",
	"Bajo Nuevo Bank (Petrel Is.)": "Banco Bajo Nuevo",
	"Baykonur Cosmodrome": "Cosmódromo de Baikonur",
	"Bir Tawil": "Bir Tawil",
	"Brazilian Island": "Isla Brasileña",
	"British Indian Ocean Territory": "Territorio Británico del Océano Índico",
	"Clipperton Island": "Isla Clipperton",
	"Coral Sea Islands": "Islas del Mar del Coral",
	"Cyprus No Mans Area": "Zona de Nadie de Chipre",
	"Dhekelia Sovereign Base Area": "Base Soberana de Dhekelia",
	"Heard Island and McDonald Islands": "Islas Heard y McDonald",
	"Indian Ocean Territories": "Territorios del Océano Índico",
	"Scarborough Reef": "Arrecife Scarborough",
	"Serranilla Bank": "Banco Serranilla",
	"Siachen Glacier": "Glaciar Siachen",
	"Southern Patagonian Ice Field": "Campo de Hielo Patagónico Sur",
	"Spratly Islands": "Islas Spratly",
	"US Naval Base Guantanamo Bay": "Base Naval de Guantánamo",
	"United States Minor Outlying Islands":
		"Islas Menores Alejadas de Estados Unidos",
};

console.log(
	"Mapeo actualizado generado con",
	Object.keys(updatedCountryNameMap).length,
	"países"
);
